### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by NiceATC** [MeLikeFish/SoT-FishAssistant#4]
Traceback (most recent call last):
  File "main.py", line 147, in <module>
  File "pyglet\shapes.py", line 479, in __init__
  File "pyglet\shapes.py", line 503, in _update_color
TypeError: 'NoneType' object cannot be interpreted as an integer

https://i.imgur.com/tiF6x1Z.png

**Comment by MeLikeFish** [comment]
Can I see your config file?

**Comment by NiceATC** [comment]
{
    "SHIPS_ENABLED": true,
    "EVENTS_ENABLED": true,
    "ON_SEA_ENABLED": true,
    "QUEST_BEGIN_ITEMS": true,
    "MERMAID_STATUES": true,
    "ENEMIES": false,
    "ROWBOATS": true,
    "SELLABLE_GOLD": true,
    "STORAGE_CRATES": true,
    "ACCES_KEYS": true,
    "SELLABLE_ORDER": true,
    "SELLABLE_ALL": true,
    "SELLABLE_ATHENAS": true,
    "SELLABLE_FORSAKEN": true,
    "DANGEROUS": true,
    "SELLABLE_MERCHANT": true,
    "SELLABLE_REAPERS": true,
    "TOMES": true,
    "PLAYER": true,
    "DEBUG": false,
    "MY_USERNAME": "MeLikeFish2559",

    "DOT_COLOR": "(50, 225, 30)",
    "DOT_SIZE": 50,

    "VERSION": 0.10
}

**Comment by NiceATC** [comment]
thx

**Comment by MeLikeFish** [comment]
Did it solve the issue?

**Comment by NiceATC** [comment]
works fine, Don't have an in-game menu yet? just by the config file?

**Comment by MeLikeFish** [comment]
sadly yes, I first want to get the x-marks the spot and cannon trajectory calculations before doing a in-game GUI. Also, I will be closing this issue now as it has been resolved, and next time please stick to the template
